### ISSUE TITLE
Some sites generate a SIGTRAP

### ISSUE THREAD

**Issue by psmedley** [psmedley/qt6-webengine-os2#7]
Similar to the attached...
[63c05b4d-007e_08-DOOBLE-exceptq.txt](https://github.com/psmedley/qt6-webengine-os2/files/10399725/63c05b4d-007e_08-DOOBLE-exceptq.txt)

**Comment by lerdmann** [comment]
This is very odd. Something implanted an "int 3" into the code (the error location actually points behind the "int 3" instruction and as you can see, the following 2 bytes seem to be the leftover of a complete instruction whose first byte was overwritten with the "int3" instruction).

That would either happen if
1) it is explicitely coded
2) if the trace facility dynamically implants an "int 3" breakpoint (if, for example, you do a "trace on jfs", then jfs.ifs will get int3´s implanted at various places in the loaded binary so that it can spit out trace info at those points)
3) if a debugger dynamically implants an "int 3" breakpoint (for about the same reason as 2), it would for example be able to display the register contents at that point)

1) is not likely as (see above) it seems that a 3-byte instruction had its first byte dynamically overwritten with an "int 3" instruction.
My gut feeling would be that under some circumstances, EXCEPTQ implants dynamic tracepoints by using the "DosDynamicTrace" API (see point 2)) but I don`t know when it would do that.

**Comment by psmedley** [comment]
I got a different SIGTRAP today in some pdfium code - when trying to save a page as PDF
[63e8992c-0040_0e-DOOBLE-exceptq.txt](https://github.com/psmedley/qt6-webengine-os2/files/10714753/63e8992c-0040_0e-DOOBLE-exceptq.txt)

Agree it's a little strange..

**Comment by psmedley** [comment]
A similar SIGTRAP printing to PDF was fixed in b400f57a8f31f7d176b4b0792a19ba4bf1eb0e84 will create a new ticket including a site URL/steps to reproduce if more are found.

**Comment by dryeo** [comment]
Some more info about browsers using TRAP 3, 
https://github.com/bitwiseworks/mozilla-os2/issues/269, note that this 
one was compiler flag influenced.
Seems some were due to OOM's (Out of Memory) conditions too.
